
*** caught segfault *** address 0x2e, cause 'memory not mapped'  Traceback:  1: py_call_impl
